### ISSUE TITLE
thinking and moves

### ISSUE THREAD

**Issue by freevryheid** [JohnAD/negamax#3]
Hi John, I see from your youtube video that you indicate on the terminal when negamax is "thinking". Not sure how you did this. Also, can negamax indicate on the terminal the move it decided on.

BTW I'm working on a chess variant: https://github.com/freevryheid/longbow that uses your nim modules. These motivated me to code the thing after thinking about it for months. I'm still trying to optimize the scoring :)

**Comment by JohnAD** [comment]
@freevryheid Using the `play()` function from the `turn-based_game` library (which negamax depends on), there is no real way to change what is shown on the terminal. But adding that to `play()` is a good idea; feel free to make a PR if motivated. :)

If you look at the code used for the `play()` function, you will see that it is fairly simple and straightforward, and you could easily write something that does that same thing. The procedure that gets the user's (or algorithm's) move is `get_move()`. Details:

https://github.com/JohnAD/turn_based_game/blob/master/docs/turn_based_game-ref.rst#get_move

In fact, the unit tests for this library avoids `play` and uses `get_move` to get the moves chosen by negamax, in order to test the correctness of the algorithm. See:

https://github.com/JohnAD/negamax/blob/master/tests/tknights.nim

**Comment by JohnAD** [comment]
Upgraded the `play` function in https://github.com/JohnAD/turn_based_game

**Comment by freevryheid** [comment]
This works, thanks!
